"""empty message

Revision ID: 24b5495e1bc5
Revises: a4eeaa897024
Create Date: 2020-10-22 21:33:29.668608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b5495e1bc5'
down_revision = 'a4eeaa897024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_post', 'text')
    # ### end Alembic commands ###
